<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BukuSeed extends Seeder
{
    public function run()
    {
        $data = [
            [
                'idk'           => 1,
                'k'             => 'teknologi',
                'created_at'    => '2021-12-18 02:15:07',
                'updated_at'    => '2021-12-18 02:15:07',
                'deleted_at'    => NULL
            ],
            [
                'idk'           => null,
                'k'             => 'sejarah',
                'created_at'    => '2021-12-18 02:15:18',
                'updated_at'    => '2021-12-18 02:15:18',
                'deleted_at'    => NULL
            ],
            [
                'idk'           => null,
                'k'             => 'sains',
                'created_at'    => '2021-12-18 02:15:22',
                'updated_at'    => '2021-12-18 02:15:22',
                'deleted_at'    => NULL
            ],
            [
                'idk'           => null,
                'k'             => 'matematika',
                'created_at'    => '2021-12-18 02:15:22',
                'updated_at'    => '2021-12-18 02:15:22',
                'deleted_at'    => NULL
            ],
            [
                'idk'           => null,
                'k'             => 'science',
                'created_at'    => '2021-12-18 02:15:22',
                'updated_at'    => '2021-12-18 02:15:22',
                'deleted_at'    => NULL
            ],
        ];
        $this->db->table('kategori')->insertBatch($data);


        $data = [
            [
                'id_buku'       => 1,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 7,
                'judul_buku'    => 'Machine Learning Basic',
                'sinopsis'      => 'Machine learning (ML) is a type of artificial intelligence (AI) that allows software applications to become more accurate at predicting outcomes without being explicitly programmed to do so. Machine learning algorithms use historical data as input to predict new output values.',
                'kategori'      => 'teknologi',
                'penulis_buku'  => 'Roudolph Russell',
                'penerbit_buku' => 'Gramedia',
                'tahun_terbit'  => '2018-01',
                'cover_buku'    => '1639815676_6692bd98d43cf0e3d5b6.jpg',
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 10,
                'judul_buku'    => 'Machine Learning For Beginner',
                'sinopsis'      => 'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
                'kategori'      => 'teknologi',
                'penulis_buku'  => 'CRIS SBASTIAN',
                'penerbit_buku' => 'Penerbit Adi',
                'tahun_terbit'  => '2013-01',
                'cover_buku'    => '1639815739_ee061d6b920416428e97.jpg',
                'created_at'    => '2021-12-18 02:23:16',
                'updated_at'    => '2021-12-18 02:24:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 15,
                'judul_buku'    => 'Machine Learning From Beginner To Master',
                'sinopsis'      => 'Machine learning is the science of getting computers to act without being explicitly programmed. In the past decade, machine learning has given us ...',
                'kategori'      => 'teknologi',
                'penulis_buku'  => 'SAMUAL HACK',
                'penerbit_buku' => 'Erlangga',
                'tahun_terbit'  => '2008-10',
                'cover_buku'    => '1639815836_c8d53a1fa5471732daff.jpg',
                'created_at'    => '2021-12-18 02:25:16',
                'updated_at'    => '2021-12-18 02:26:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 14,
                'judul_buku'    => 'BREATH The New Science Of A Lost Art',
                'sinopsis'      => 'Science is the pursuit and application of knowledge and understanding of the natural and social world following a systematic methodology based on evidence',
                'kategori'      => 'sains',
                'penulis_buku'  => 'James Nestor',
                'penerbit_buku' => 'Gramedia',
                'tahun_terbit'  => '2012-05',
                'cover_buku'    => '1639815952_73b0c7c9401c704acb46.jpg',
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 11,
                'judul_buku'    => 'The Earth Book',
                'sinopsis'      => 'Earth is our home planet. Scientists believe Earth and its moon formed around the same time as the rest of the solar system. Earth is the fifth-largest planet in the solar system. Its diameter is about 8,000 miles. And Earth is the third-closest planet to the sun',
                'kategori'      => 'sains',
                'penulis_buku'  => 'Miles Kelly',
                'penerbit_buku' => 'Erlangga',
                'tahun_terbit'  => '2019-03',
                'cover_buku'    => '1639816017_58737bc932038bec7c03.png',
                'created_at'    => '2021-12-18 02:29:16',
                'updated_at'    => '2021-12-18 02:30:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 9,
                'judul_buku'    => 'Paper World Planet Earth',
                'sinopsis'      => 'Earth is our home planet. Scientists believe Earth and its moon formed around the same time as the rest of the solar system. Earth is the fifth-largest planet in the solar system. Its diameter is about 8,000 miles. And Earth is the third-closest planet to the sun',
                'kategori'      => 'sains',
                'penulis_buku'  => '-',
                'penerbit_buku' => 'BOMBOLAND',
                'tahun_terbit'  => '2020-07',
                'cover_buku'    => '1639816106_80ed44baf4b7fcebd0ba.jpeg',
                'created_at'    => '2021-12-18 02:31:16',
                'updated_at'    => '2021-12-18 02:32:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 6,
                'judul_buku'    => 'A History Of The Bibel',
                'sinopsis'      => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas repudiandae sequi laudantium, ducimus laborum autem reprehenderit explicabo quaerat aliquid ipsam cumque, sapiente quidem illum enim, nulla officia voluptate in adipisci.',
                'kategori'      => 'sejarah',
                'penulis_buku'  => 'Jhon Barton',
                'penerbit_buku' => 'Penerbit Adi',
                'tahun_terbit'  => '1997-06',
                'cover_buku'    => '1639816177_542ce3d779e1d32fc85c.jpg',
                'created_at'    => '2021-12-18 02:33:16',
                'updated_at'    => '2021-12-18 02:34:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 14,
                'judul_buku'    => 'World History ',
                'sinopsis'      => 'World history or global history as a field of historical study examines history from a global perspective. It emerged centuries ago; leading practitioners ...',
                'kategori'      => 'sejarah',
                'penulis_buku'  => 'Krishna Reddy',
                'penerbit_buku' => 'Gramedia',
                'tahun_terbit'  => '2018-12',
                'cover_buku'    => '1639816261_0241a51d012624309ff2.jpg',
                'created_at'    => '2021-12-18 02:35:16',
                'updated_at'    => '2021-12-18 02:36:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 11,
                'judul_buku'    => 'World History 4Th Edition',
                'sinopsis'      => 'World history or global history as a field of historical study examines history from a global perspective. It emerged centuries ago; leading practitioners ...',
                'kategori'      => 'sejarah',
                'penulis_buku'  => 'Adam Brown',
                'penerbit_buku' => 'Republika',
                'tahun_terbit'  => '2021-06',
                'cover_buku'    => '1639816306_416d8b6bd841dd48651b.jpg',
                'created_at'    => '2021-12-18 02:37:16',
                'updated_at'    => '2021-12-18 02:38:16',
                'deleted_at'    => NULL
            ],
            [
                'id_buku'       => null,
                'kode_buku'     => uniqid(),
                'stok_buku'     => 14,
                'judul_buku'    => 'The Book Of Homeless Ness',
                'sinopsis'      => 'Homelessness is lacking stable and appropriate housing. People can be categorized as homeless if they are: living on the streets; moving between temporary shelters, including houses of friends, family and emergency accommodation; living in private boarding houses without a private bathroom or security of tenure',
                'kategori'      => 'sejarah',
                'penulis_buku'  => '-',
                'penerbit_buku' => 'Republika',
                'tahun_terbit'  => '2019-10',
                'cover_buku'    => '1639816363_bb0433a44ce309940ba0.jpg',
                'created_at'    => '2021-12-18 02:39:16',
                'updated_at'    => '2021-12-18 02:40:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "History of Programming Languages",
                "sinopsis"      => "This specially prepared work comprises a living archive of important programming languages, described by the people most instrumental in their creation and development. Drawn from the ACM/SIGPLAN Second History of Programming Languages Conference, this volume, like the earlier book from the first su...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Thomas J. Bergin, Richard G. Gibson",
                "penerbit_buku" => "Addison-Wesley",
                "tahun_terbit"  => "1996",
                "cover_buku"    => "9780201895025.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "The Game Console",
                "sinopsis"      => "The Game Console is a tour through the evolution of video game hardware, with gorgeous full-color photos of 86 consoles and their grisly innards. You'll start your journey with legendary consoles like the Magnavox Odyssey, Atari 2600, Nintendo Entertainment System, and the Commodore 64. The visual n...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Evan Amos",
                "penerbit_buku" => "No Starch Press",
                "tahun_terbit"  => "2018",
                "cover_buku"    => "9781593277437.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Algorithms",
                "sinopsis"      => "Algorithms are the lifeblood of computer science. They are the machines that proofs build and the music that programs play. Their history is as old as mathematics itself. This book is a wide-ranging, idiosyncratic treatise on the design and analysis of algorithms, covering several fundamental techni...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Jeff Erickson",
                "penerbit_buku" => "Self-publishing",
                "tahun_terbit"  => "2019",
                "cover_buku"    => "1001590577478.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "PostgreSQL for Beginners",
                "sinopsis"      => "PostgreSQL for Beginners book is intended for those who only start getting acquainted with the world of PostgreSQL. It contains some basic information about this DBMS and its main features, history of its creation and development roadmap, step-by-step installation instructions and a getting started ...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Pavel Luzanov, Egor Rogov, Igor Levshin",
                "penerbit_buku" => "Self-publishing",
                "tahun_terbit"  => "2019",
                "cover_buku"    => "1001591362411.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "The CSS Handbook",
                "sinopsis"      => "CSS, a shorthand for Cascading Style Sheets, is one of the main building blocks of the Web. Its history goes back to the 90's and along with HTML it has changed a lot since its humble beginnings.This handbook is aimed at a vast audience.- First, the beginner. I explain CSS from zero in a succinct bu...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Flavio Copes",
                "penerbit_buku" => "Self-publishing",
                "tahun_terbit"  => "2019",
                "cover_buku"    => "1001629809178.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Philosophy of Computer Science",
                "sinopsis"      => "This book looks at some of the central issues in the philosophy of computer science. It is not designed to answer all (or even any) of the philosophical questions that can be raised about the nature of computing, computers, and computer science. Rather, it is designed to &quot;bring you up to speed&...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "William Rapaport",
                "penerbit_buku" => "Self-publishing",
                "tahun_terbit"  => "2020",
                "cover_buku"    => "1001629809245.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Cocoa Programming Developer's Handbook",
                "sinopsis"      => "The Cocoa programming environment - Apple's powerful set of clean, object-oriented APIs - is increasingly becoming the basis of almost all contemporary Mac OS X development. With its long history of constant refinement and improvement, Cocoa has matured into a sophisticated programming environment t...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "David Chisnall",
                "penerbit_buku" => "Addison-Wesley",
                "tahun_terbit"  => "2010",
                "cover_buku"    => "9780321639639.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "A Game Design Vocabulary",
                "sinopsis"      => "Why aren't videogames getting better? Why does it feel like we're playing the same games, over and over again? Why aren't games helping us transform our lives, like great music, books, and movies do?The problem is language. We still don't know how to talk about game design. We can't share our vision...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Anna Anthropy, Naomi Clark",
                "penerbit_buku" => "Addison-Wesley",
                "tahun_terbit"  => "2014",
                "cover_buku"    => "9780321886927.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Professional ASP.NET MVC 1.0",
                "sinopsis"      => "This book begins with you working along as Scott Guthrie builds a complete ASP.NET MVC reference application. He begins NerdDinner by using the File-&gt;New Project menu command within Visual Studio to create a new ASP.NET MVC Application. You'll then incrementally add functionality and features. Al...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Rob Conery, Scott Hanselman, Phil Haack, Scott Guthrie",
                "penerbit_buku" => "Wrox",
                "tahun_terbit"  => "2009",
                "cover_buku"    => "9780470384619.png",
                'created_at'    => '2021-12-18 02:21:16',
                'updated_at'    => '2021-12-18 02:22:16',
                'deleted_at'    => NULL
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Mathematica Cookbook",
                "sinopsis"      => "Mathematica Cookbook helps you master the application's core principles by walking you through real-world problems. Ideal for browsing, this book includes recipes for working with numerics, data structures, algebraic equations, calculus, and statistics. You'll also venture into exotic territory with...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Sal Mangano",
                "penerbit_buku" => "O'Reilly Media",
                "tahun_terbit"  => "2010",
                "cover_buku"    => "9780596520991.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Mathematical Structures for Computer Graphics",
                "sinopsis"      => "Mathematical Structures for Computer Graphics presents an accessible and intuitive approach to the mathematical ideas and techniques necessary for two- and three-dimensional computer graphics. Focusing on the significant mathematical results, the book establishes key algorithms used to build complex...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Steven J. Janke",
                "penerbit_buku" => "Wiley",
                "tahun_terbit"  => "2014",
                "cover_buku"    => "9781118712191.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "MATLAB Mathematical Analysis",
                "sinopsis"      => "MATLAB Mathematical Analysis is a reference book that presents the techniques of mathematical analysis through examples and exercises resolved with MATLAB software. The purpose is to give you examples of the mathematical analysis functions offered by MATLAB so that you can use them in your daily wor...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Cesar Perez Lopez",
                "penerbit_buku" => "Apress",
                "tahun_terbit"  => "2014",
                "cover_buku"    => "9781484203507.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Math Mutation Classics",
                "sinopsis"      => "Did you know that sometimes 2+2 equals 5? That wheels don't always have to be round? That you can mathematically prove there is a hippopotamus in your basement? Or how to spot four-dimensional beings as they pass through your kitchen? If not, then you need to read Math Mutation Classics.This is a co...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Erik Seligman",
                "penerbit_buku" => "Apress",
                "tahun_terbit"  => "2016",
                "cover_buku"    => "9781484218914.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Pro Deep Learning with TensorFlow",
                "sinopsis"      => "Deploy deep learning solutions in production with ease using TensorFlow. You'll also develop the mathematical understanding and intuition required to invent new deep learning architectures and solutions on your own.Pro Deep Learning with TensorFlow provides practical, hands-on expertise so you can l...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Santanu Pattanayak",
                "penerbit_buku" => "Apress",
                "tahun_terbit"  => "2017",
                "cover_buku"    => "9781484230954.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Practical Python AI Projects",
                "sinopsis"      => "Discover the art and science of solving artificial intelligence problems with Python using optimization modeling. This book covers the practical creation and analysis of mathematical algebraic models such as linear continuous models, non-obviously linear continuous models, and pure linear integer mo...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Serge Kruk",
                "penerbit_buku" => "Apress",
                "tahun_terbit"  => "2018",
                "cover_buku"    => "9781484234228.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Raspbian OS Programming with the Raspberry Pi",
                "sinopsis"      => "Master the command line and Raspbian Linux as well as the physical connections of the Pi. With this book you'll develop skills applicable to other real world applications in both hardware and software development all while working on simple and fun IoT projects that you can do yourself.You'll learn ...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Agus Kurniawan",
                "penerbit_buku" => "Apress",
                "tahun_terbit"  => "2019",
                "cover_buku"    => "9781484242117.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Beginning Mathematica and Wolfram for Data Science",
                "sinopsis"      => "Enhance your data science programming and analysis with the Wolfram programming language and Mathematica, an applied mathematical tools suite. The book will introduce you to the Wolfram programming language and its syntax, as well as the structure of Mathematica and its advantages and disadvantages....",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Jalil Villalobos Alva",
                "penerbit_buku" => "Apress",
                "tahun_terbit"  => "2021",
                "cover_buku"    => "9781484265932.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "NumPy Beginner's Guide, 2nd Edition",
                "sinopsis"      => "NumPy is an extension to, and the fundamental package for scientific computing with Python. In today's world of science and technology, it is all about speed and flexibility. When it comes to scientific computing, NumPy is on the top of the list.NumPy Beginner's Guide will teach you about NumPy, a l...",
                "kategori"      => "teknologi",
                "penulis_buku"  => "Ivan Idris",
                "penerbit_buku" => "Packt Publishing",
                "tahun_terbit"  => "2013",
                "cover_buku"    => "9781782166085.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "The Computer Science Activity Book",
                "sinopsis"      => "The Computer Science Activity Book is the perfect companion for curious youngsters - or grown-ups who think they'll never understand some of the basics of how computers work. Work through this brief, coloring book-like collection of fun and innovative hands-on exercises and learn some basic programm...",
                "kategori"      => "science",
                "penulis_buku"  => "Christine Liu, Tera Johnson",
                "penerbit_buku" => "No Starch Press",
                "tahun_terbit"  => "2018",
                "cover_buku"    => "9781593279103.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Philosophy of Computer Science",
                "sinopsis"      => "This book looks at some of the central issues in the philosophy of computer science. It is not designed to answer all (or even any) of the philosophical questions that can be raised about the nature of computing, computers, and computer science. Rather, it is designed to &quot;bring you up to speed&...",
                "kategori"      => "science",
                "penulis_buku"  => "William Rapaport",
                "penerbit_buku" => "Self-publishing",
                "tahun_terbit"  => "2020",
                "cover_buku"    => "1001629809245.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Introduction to Computer Science Using Python",
                "sinopsis"      => "Introduction to Computer Science Using Python: A Computational Problem-Solving Focusintroduces students to programming and computational problem-solving via a back-to-basics, step-by-step, objects-late approach that makes this book easy to teach and learn from. Students are provided with a thorough ...",
                "kategori"      => "science",
                "penulis_buku"  => "Charles Dierbach",
                "penerbit_buku" => "Wiley",
                "tahun_terbit"  => "2013",
                "cover_buku"    => "9780470555156.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Computer Science Programming Basics in Ruby",
                "sinopsis"      => "If you know basic high-school math, you can quickly learn and apply the core concepts of computer science with this concise, hands-on book. Led by a team of experts, you'll quickly understand the difference between computer science and computer programming, and you'll learn how algorithms help you s...",
                "kategori"      => "science",
                "penulis_buku"  => "Ophir Frieder, Gideon Frieder, David Grossman",
                "penerbit_buku" => "O'Reilly Media",
                "tahun_terbit"  => "2013",
                "cover_buku"    => "9781449355975.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Lauren Ipsum",
                "sinopsis"      => "Lauren Ipsum is a whimsical journey through a land where logic and computer science come to life.Meet Lauren, an adventurer lost in Userland who needs to find her way home by solving a series of puzzles. As she visits places like the Push &amp;amp; Pop Cafe and makes friends with people like Hugh Ru...",
                "kategori"      => "science",
                "penulis_buku"  => "Carlos Bueno",
                "penerbit_buku" => "No Starch Press",
                "tahun_terbit"  => "2014",
                "cover_buku"    => "9781593275747.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Classic Computer Science Problems in Swift",
                "sinopsis"      => "Don't just learn another language. Become a better programmer instead. Today's awesome iOS apps stand on the shoulders of classic algorithms, coding techniques, and engineering principles. Master these core skills in Swift, and you'll be ready for AI, data-centric programming, machine learning, and ...",
                "kategori"      => "science",
                "penulis_buku"  => "David Kopec",
                "penerbit_buku" => "Manning",
                "tahun_terbit"  => "2018",
                "cover_buku"    => "9781617294891.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Classic Computer Science Problems in Python",
                "sinopsis"      => "Classic Computer Science Problems in Python deepens your knowledge of problem solving techniques from the realm of computer science by challenging you with time-tested scenarios, exercises, and algorithms. As you work through examples in search, clustering, graphs, and more, you'll remember importan",
                "kategori"      => "science",
                "penulis_buku"  => "David Kopec",
                "penerbit_buku" => "Manning",
                "tahun_terbit"  => "2019",
                "cover_buku"    => "9781617295980.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Coding in the Classroom",
                "sinopsis"      => "Computer science opens more doors for today's youth than any other discipline - which is why Coding in the Classroom is your key to unlocking students' future potential. Author Ryan Somma untangles the current state of CS education standards; describes the cognitive, academic, and professional benef...",
                "kategori"      => "science",
                "penulis_buku"  => "Ryan Somma",
                "penerbit_buku" => "No Starch Press",
                "tahun_terbit"  => "2020",
                "cover_buku"    => "9781718500341.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "Practical Programming",
                "sinopsis"      => "Welcome to computer science in the 21st century. Did you ever wonder how computers represent DNA? How they can download a web page containing population data and analyze it to spot trends? Or how they can change the colors in a color photograph? If so, this book is for you. By the time you're done",
                "kategori"      => "science",
                "penulis_buku"  => "Jennifer Campbell, Paul Gries, Jason Montojo, Greg Wilson",
                "penerbit_buku" => "The Pragmatic Programmers",
                "tahun_terbit"  => "2009",
                "cover_buku"    => "9781934356272.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ],
            [
                "id_buku"       => null,
                "kode_buku"     => uniqid(),
                "stok_buku"     => 15,
                "judul_buku"    => "The Definitive Guide to How Computers Do Math",
                "sinopsis"      => "The Basics of Computer Arithmetic Made Enjoyable and Accessible-with a Special Program Included for Hands-on Learning.Packed with nuggets of information and tidbits of trivia, How Computers Do Math provides an incredibly fun and interesting introduction to the way in which computers perform theirma...",
                "kategori"      => "science",
                "penulis_buku"  => "Clive Maxfield, Alvin Brown",
                "penerbit_buku" => "Wiley",
                "tahun_terbit"  => "2005",
                "cover_buku"    => "9780471732785.png",
                'created_at'    => '2021-12-18 02:27:16',
                'updated_at'    => '2021-12-18 02:28:16',
                'deleted_at'    => NULL,
            ]
        ];
        $this->db->table('buku')->insertBatch($data);
    }
}
